name: pydata
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - pandas=1.*
  - numpy
  - notebook
  - jupyter_contrib_nbextensions
  - rise
  - isort
  - jupyter
  - statsmodels
